== Strings
The file vw_strings.bas is intended to list all of the strings the macro will use that are not native to Visio

If any string should need to change it should be done in this file.

=== String Details
The code is written such that it is self-documenting, should any item appear to be obscure in name a comment will be written above to supplement.

=== String Functions
[horizontal]
GenList:: `public function` returns a Visio ShapeSheet Format List of the input items
+
[horizontal]
Return Type:: [blue]#String#
Arguments::
+
[cols="1,1,5", frame=none, grid=none, options=header]
|===
| Type | Identifier | Description
| [blue]#ParamArray# | items | List of string values to group as a list
|===

+

[horizontal]
LegalName:: `public function` returns acceptable name for NamedRows
+
[horizontal]
Return Type:: [blue]#String#
Arguments::
+
[cols="1,1,5", frame=none, grid=none, options=header]
|===
| Type | Identifier | Description
| [blue]#String# | str | String to remove special characters and spaces
|===
