== Types

The vw_types.bas module is responsible for handling a Visio Shape's PageSheet content to make sure the Shape Type and Events on the Shape are defined properly.

This module will contain constant values, enumerations, subroutines and functions for dealing with Shape and Event Types.

Every shape created by Visio Waves will have a User-defined cell named Type where the value stores the type of shape it is, following the table below
[horizontal]
Shape Type:: *Description*
Void:: Type value has not been set
Signal:: Mask for Clock, Bit, or Bus
Data:: Mask for Bit or Bus
Clock:: Indicates signal is a clock
Bit:: Indicates signal is a bit
Bus:: Indicates signal is a bus
Child:: Mask for Label, Node, or Gate
Label:: Indicates the shape is a label
Node:: Indicates the shape is a node
Gate:: Indicates the shape is a GateX/DriveX
Gap:: Indicates the shape is a gap/spacer indicating some time has passed

Event Triggers are used to determine when the event should occur, this is mostly to relay information to the user as the trigger is NOT stored within the shape.
[horizontal]
Event Trigger:: *Description*
Absolute:: An absolute position on the ContainingPage of the shape
Relative:: A position relative to the shape itself
Edge:: Any transition on the shape
Posedge:: Any rising transition on the shape (excluding gates)
Negedge:: Any falling transition on the shape (excluding gates)

Events are stored in rows of the Visio Waves Shape's PageSheet where the section and column is are determined by constants VW_EVENT_SECTION and VW_EVENT_SECTION_COL. We use additional enumerations to describe what and how data is stored in these rows.

Event Fields describe the indices of the cell containing event data, while Event Masks are used to parse the cell to obtain the data
[horizontal]
Event Field:: *Value*
F_BIT_1:: 2^30
F_BIT_0:: 2^29
F_GAP:: 2^20
F_NODE:: 2^19
F_LABEL:: 2^18
F_GATE:: 2^17
F_EVENT:: 2^16
+
[horizontal]
Event Mask:: *Value*
ROW_MASK::   &h00FFFF
EVENT_MASK:: &h030000
CHILD_MASK:: &h1C0000
BIT_MASK:: &h30000000

From the programming perspective only GATE and EDGE events exists. From the user perspective Gaps, Nodes, Labels, etc are all items that can be added to a shape. Therefore, no enumeration exists for Event Types and we want to follow these rules:

. If F_EVENT = 0, F_GAP is the only field that can be non-zero if and only if the shape is linked to another shape with an F_GAP field set
. If F_EVENT = 1 and F_GATE = 0 then the EVENT is an EDGE
.. The fields F_BIT_1 and F_BIT_0 are don't care's for EDGE
. If F_EVENT = 1 and F_GATE = 1 then the EVENT is a GATE
.. F_LABEL must be 0 for a GATE
.. If F_BIT_0 = 0 and F_BIT_1 = 0 then the EVENT is also a GATE_X/DRIVE_X
.. If F_BIT_0 = 1 and F_BIT_1 = 1 then the EVENT is also a GATE_Z/DRIVE_Z
.. If F_BIT_0 = 1 and F_BIT_1 = 0 then the EVENT is also a GATE_0/DRIVE_0
.. If F_BIT_0 = 0 and F_BIT_1 = 1 then the EVENT is also a GATE_1/DRIVE_1
... F_BIT_0 and F_BIT_1 are absolute and will not respond to inverting the shape
 