== Types

The vw_types.bas module is responsible for handling a Visio Shape's PageSheet content to make sure the Shape Type and Events on the Shape are defined properly.

This module will contain constant values, enumerations, subroutines and functions for dealing with Shape and Event Types.

Every shape created by Visio Waves will have a User-defined cell named Type where the value stores the type of shape it is, following the table below
[horizontal]
Shape Type:: *Description* (Value)
Void:: Type value has not been set (0)
Signal:: Mask for Clock, Bit, or Bus (7)
Data:: Mask for Bit or Bus (3)
Clock:: Indicates signal is a clock (4)
Bit:: Indicates signal is a bit (1)
Bus:: Indicates signal is a bus (2)
Child:: Mask for Label, Node, or Gate (120)
Label:: Indicates the shape is a label (8)
Node:: Indicates the shape is a node (16)
Gate:: Indicates the shape is a GateX/DriveX (32)
Gap:: Indicates the shape is a gap/spacer indicating some time has passed (64)

Event Triggers are used to determine when the event should occur, this is NOT stored within the shape.
[horizontal]
Event Trigger:: *Description* (Value)
Absolute:: An absolute position on the ContainingPage of the shape (4)
Relative:: A position relative to the shape itself (12)
+
_Relative is kept as 12 to indicate this is a number instead of an index of an existing transition on the Shape_
Edge:: Any transition on the shape (3)
Posedge:: Any rising transition on the shape (1)
Negedge:: Any falling transition on the shape (2)
+
_Edge, Posedge, and Negedge triggers are linked to the super-ceding geometry. If the edge of a reference signal changes so will the event added using this.

Events are stored in rows of the Visio Waves Shape's PageSheet where the section and column is are determined by constants VW_EVENT_SECTION and VW_EVENT_SECTION_COL. We use additional enumerations to describe what and how data is stored in these rows.

Event Fields describe the indices of the cell containing event data, while Event Masks are used to parse the cell to obtain the data
[horizontal]
Event Field:: *Value*
F_BIT_1:: 2^30
F_BIT_0:: 2^29
F_GAP:: 2^20
F_NODE:: 2^19
F_LABEL:: 2^18
F_GATE:: 2^17
F_EVENT:: 2^16
+
[horizontal]
Event Mask:: *Value*
ROW_MASK::   &h00FFFF
EVENT_MASK:: &h030000
CHILD_MASK:: &h1C0000
BIT_MASK:: &h30000000

From the programming perspective only GATE and EDGE events exists. From the user perspective Gaps, Nodes, Labels, etc are all items that can be added to a shape. Therefore, no enumeration exists for Event Types and we want to follow these rules:

. If F_EVENT = 0, F_GAP is the only field that can be non-zero if and only if the shape is linked to another shape with an F_GAP field set
. If F_EVENT = 1 and F_GATE = 0 then the EVENT is an EDGE
.. The fields F_BIT_1 and F_BIT_0 are don't care's for EDGE
. If F_EVENT = 1 and F_GATE = 1 then the EVENT is a GATE
.. F_LABEL must be 0 for a GATE
.. If F_BIT_0 = 0 and F_BIT_1 = 0 then the EVENT is also a GATE_X/DRIVE_X
.. If F_BIT_0 = 1 and F_BIT_1 = 1 then the EVENT is also a GATE_Z/DRIVE_Z
.. If F_BIT_0 = 1 and F_BIT_1 = 0 then the EVENT is also a GATE_0/DRIVE_0
.. If F_BIT_0 = 0 and F_BIT_1 = 1 then the EVENT is also a GATE_1/DRIVE_1
... F_BIT_0 and F_BIT_1 are absolute and will not respond to inverting the shape

=== Notes on Types

TBD. Who is responsible for this data and enforcing it???

If the code is done in vw_types.bas these rules are kept together but the file name is deceiving. Strings is already doing this with two functions. How many functions do we need for these rules?

. Function GetRow
+
[%hardbreaks]
Using _ROW_MASK_ return the Geometry1 Row of the data.
Needed to manage the geometry.
[red]#TBD. What about the Geometry section for line endings???#
The sections are one to one with the scratch rows as Bus types do not have additional geometry and cannot show line endings
[red]#TBD. What to do if the shape is converted to PolyLine???#
[yellow]#TBD. What is the savings on say an AXI diagram by converting to Polyline???#
A PolyLine can be used to draw DriveX but then the LineEndings strategy is lost, it would be better to add DriveX as it's own shape, we don't want a bunch of line endings as shapes. Would closing the shape fix that??? [red]#No#

. Function AddEvent
+
[%hardbreaks]
There would be different variations of this function used to manage the events on the shape.
+
.. Add/Remove Edge, we can let the Signal decided what type of Edge this is, Positive Negative.
... The problem is we know it is better performance to determine that after adding all events.
... _With the exception of a clock, events are added by the user one by one and this should not matter._
.. Add/Remove GateX, as of now this is looking to be an entirely new shape but should be called the same way as Add/Remove Edge and also modify the Signal's Geometry1 to avoid overlapping while hiding any additional Geometry Sections through NoLine = True
.. Add/Remove Gate0/1, no need to be a new shape just pull to the direction of the version indicated
.. Add/Remove GateZ, as of now no new shape, but for colorization maybe, can use additional geometry with NoLine = True and Fill = Gold
.. Add/Remove Label, child shape where PinX = Scratch.X~i and PinY = Parent!PinY + Parent!Height + Height???
.. Add/Remove Node, child shape where PinX TBD and PinY = Parent!PinY + (Parent!Height/2)
.. Add/Remove Gap, child shape where PinX TBD and PinY = Parent!PinY + Parent!Height


=== Notes

Phase::
* Wavedrom does not let the user control the signal delay before a clock edge
* Wavedrom appears to add an unknown delay and subtract for phase
* Wavedrom does not complete signals when Phase does not make sense to it, it should complete the signal width rather than truncate or shift the signal to the right on the diagram.
* In Wavedrom 180 degree phase right = 1, 180 left = -1, etc.
