Attribute VB_Name = "VBAReset"

' Generated by Python Script! Edit iif you know what you are doing
' Use after enabling Macro Settings -> Allow Programmatic Access to VBProject

Private Sub VBA_Delete()
  Do While ThisDocument.VBProject.VBComponents.Count > 2
    For Each vbComp in ThisDocument.VBProject.VBComponents
      If vbComp.Name <> "ThisDocument" And vbComp.Name <> "VBAReset" Then _
        ThisDocument.VBProject.VBComponents.Remove vbComp
    Next
    If ThisDocument.VBProject.VBComponents.Count > 2 Then Stop
  Loop
End Sub

Public Sub VBA_Reset()
  On Error Resume Next
  Dim MyComponents as Collection
  Set MyComponents = New Collection
  MyComponents.Add "D:\Visio Projects\Visio Waves\Modules\vw_page_cfg.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Modules\vw_strings.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Modules\vw_types.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_activelow_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_buswidth_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_childoffset_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_dutycycle_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_i_delay_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_labeledges_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_labelfont_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_labelshape_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_labelsize_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_nodefont_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_nodesizemult_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_period_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_showdimensions_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_signalskew_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_skewwidth_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_skew_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_s_delay_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Tests\vw_test_pageconfig.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Tests\vw_test_types.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Tests\vw_visio_wrapper_test.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Visio_Shape_Wrapper\visio_shape_wrapper_c.cls"
  VBA_Delete
  For Each vbComp in MyComponents
    Application.VBE.ActiveVBProject.VBComponents.Import vbComp
  Next
End Sub

Public Sub UpdateComponent(vbCompName as String)
  On Error Resume Next
  Dim MyComponents as Collection
  Set MyComponents = New Collection
  MyComponents.Add "D:\Visio Projects\Visio Waves\Modules\vw_page_cfg.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Modules\vw_strings.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Modules\vw_types.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_activelow_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_buswidth_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_childoffset_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_dutycycle_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_i_delay_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_labeledges_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_labelfont_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_labelshape_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_labelsize_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_nodefont_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_nodesizemult_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_period_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_showdimensions_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_signalskew_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_skewwidth_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_skew_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Option_Classes\option_s_delay_c.cls"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Tests\vw_test_pageconfig.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Tests\vw_test_types.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Tests\vw_visio_wrapper_test.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Visio_Shape_Wrapper\visio_shape_wrapper_c.cls"
  For Each vbComp in ThisDocument.VBProject.VBComponents
    If LCase(vbComp.Name) = vbCompName Then
      ThisDocument.VBProject.VBComponents.Remove vbComp
    EndIf
  Next
  For Each vbComp in MyComponents
    If Instr(vbComp, vbCompName) > 0 Then _
      Application.VBE.ActiveVBProject.VBComponents.Import vbComp
  Next
End Sub
