Attribute VB_Name = "VBAReset"

' Generated by Python Script! Edit iif you know what you are doing
' Use after enabling Macro Settings -> Allow Programmatic Access to VBProject

Public Sub VBA_Reset()
  On Error Resume Next
  Dim MyComponents as Collection
  Set MyComponents = New Collection
  MyComponents.Add "D:\Visio Projects\Visio Waves\Modules\vw_strings.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Modules\vw_types.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Tests\vw_test_types.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Tests\vw_visio_wrapper_test.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Visio_Shape_Wrapper\visio_shape_wrapper_c.cls"
  Do While ThisDocument.VBProject.VBComponents.Count > 2
    For Each vbComp in ThisDocument.VBProject.VBComponents
      If Left$(vbComp.Name, 3) = "vw_" Then
        ThisDocument.VBProject.VBComponents.Remove vbComp
      ElseIf Left$(vbComp.Name, 6) = "visio_" Then
        ThisDocument.VBProject.VBComponents.Remove vbComp
      EndIf
    Next
    If ThisDocument.VBProject.VBComponents.Count > 2 Then Stop
  Loop
  For Each vbComp in MyComponents
    Application.VBE.ActiveVBProject.VBComponents.Import vbComp
  Next
End Sub

Public Sub UpdateComponent(vbCompName as String)
  On Error Resume Next
  Dim MyComponents as Collection
  Set MyComponents = New Collection
  MyComponents.Add "D:\Visio Projects\Visio Waves\Modules\vw_strings.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Modules\vw_types.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Tests\vw_test_types.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Tests\vw_visio_wrapper_test.bas"
  MyComponents.Add "D:\Visio Projects\Visio Waves\Visio_Shape_Wrapper\visio_shape_wrapper_c.cls"
  For Each vbComp in ThisDocument.VBProject.VBComponents
    If LCase(vbComp.Name) = vbCompName Then
      ThisDocument.VBProject.VBComponents.Remove vbComp
    EndIf
  Next
  For Each vbComp in MyComponents
    If Instr(vbComp, vbCompName) > 0 Then _
      Application.VBE.ActiveVBProject.VBComponents.Import vbComp
  Next
End Sub
